/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/layout/Avatar.vue')['default']
    Editable: typeof import('./src/components/layout/Editable.vue')['default']
    EditUserDialog: typeof import('./src/components/EditUserDialog.vue')['default']
    Header: typeof import('./src/components/template/template2/header.vue')['default']
    Header1: typeof import('./src/components/element/header/header1.vue')['default']
    ImgCutter: typeof import('./src/components/ImgCutter.vue')['default']
    Resume: typeof import('./src/components/resume.vue')['default']
    Resume_grid: typeof import('./src/components/resume_grid.vue')['default']
    ResumeCanvas: typeof import('./src/components/ResumeCanvas.vue')['default']
    ResumeEditor: typeof import('./src/components/ResumeEditor.vue')['default']
    ResumeElement: typeof import('./src/components/ResumeElement.vue')['default']
    ResumeSidebar: typeof import('./src/components/ResumeSidebar.vue')['default']
    ResumeToolbar: typeof import('./src/components/ResumeToolbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Template1: typeof import('./src/components/template/template1/index.vue')['default']
    Template1Header: typeof import('./src/components/template/template1/template1-header.vue')['default']
    Template2: typeof import('./src/components/template/template2/index.vue')['default']
    Template2header: typeof import('./src/components/template/template2/template2header.vue')['default']
    Template2Header: typeof import('./src/components/template/template2/template2-header.vue')['default']
    UserInfo: typeof import('./src/components/layout/userInfo.vue')['default']
  }
}
